server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name:

  datasource:
    url: jdbc:postgresql://ep-quiet-boat-a16utmwz.ap-southeast-1.aws.neon.tech/identify?user=identify_owner&password=UM7R3wdspzTy&sslmode=require
    username: identify_owner
    password: UM7R3wdspzTy
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key: "Ndq0nV6wslreZuvaL/sS/UzE5Ka9yEOQ7Og8c0m9Si3ylMn2xql5mMIhtnlzow9Nnk90MMcGs4lYIIHk2Za0tW/aAdnKmLwk4U+Ph3D22uU="
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

